name: 'terratest for Kubernetes Configurations'
description: 'Runs terratest for Kubernetes cluster creations.'
author: 'Tom Elliott <tom.w.elliott@gmail.com>'
branding:
  icon: 'terminal'
  color: 'purple'
runs:
  using: 'docker'
  image: './Dockerfile'
