name: 'Test'
on:
  pull_request:
  push:
  schedule:
  - cron: "0 21 * * 5" # Run at 11pm every Friday for weekend fixes

env:
  tf_version: '0.13.6'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@master
    - name: 'Init - GKE'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.tf_version }}
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: 'testdata/gke'
        tf_actions_comment: false
    - name: 'Validate - GKE'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.tf_version }}
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: 'testdata/gke'
        tf_actions_comment: false
    - name: 'Init - DigitalOcean'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.tf_version }}
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: 'testdata/digitalocean'
        tf_actions_comment: false
    - name: 'Validate - DigitalOcean'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.tf_version }}
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: 'testdata/digitalocean'
        tf_actions_comment: false
  do:
    runs-on: ubuntu-latest
    name: DigitalOcean
    needs: validate
    strategy:
      fail-fast: false
      matrix:
        run: [1]
      max-parallel: 3
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Test
        uses: ./.github/actions/terratest
        with:
          args: -run TestDigitalOcean
    env:
      TF_VAR_digitalocean_token: ${{ secrets.DigitalOceanToken }}
      TF_VAR_cluster_name: test-${{ github.run_id }}-${{matrix.run}}
  gke:
    runs-on: ubuntu-latest
    needs: validate
    name: GKE
    strategy:
      fail-fast: false
      matrix:
        run: [1]
      max-parallel: 3
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Test
        uses: ./.github/actions/terratest
        with:
          args: -run TestGKE
    env:
      TF_VAR_gcloud_credentials_base64: ${{ secrets.GCloudCredentialsBase64 }}
      TF_VAR_cluster_name: test-${{ github.run_id }}-${{matrix.run}}
