name: 'Test'
on: [push]

jobs:
  civo:
    runs-on: ubuntu-latest
    name: Civo
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Test
        uses: ./.github/actions/terratest
        with:
          args: -run TestCivo
    env:
      TF_VAR_civo_api_key: ${{ secrets.CivoApiKey }}
  do:
    runs-on: ubuntu-latest
    name: DigitalOcean
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Test
        uses: ./.github/actions/terratest
        with:
          args: -run TestDigitalOcean -count 10
    env:
      TF_VAR_digitalocean_token: ${{ secrets.DigitalOceanToken }}
