name: 'Test'
on: [push]

jobs:
  do:
    runs-on: ubuntu-latest
    name: DigitalOcean
    strategy:
      fail-fast: false
      matrix:
        run: [1]
      max-parallel: 3
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Test
        uses: ./.github/actions/terratest
        with:
          args: -run TestDigitalOcean
    env:
      TF_VAR_digitalocean_token: ${{ secrets.DigitalOceanToken }}
      TF_VAR_cluster_name: test-${{ github.run_id }}-${{matrix.run}}
  gke:
    runs-on: ubuntu-latest
    name: GKE
    strategy:
      fail-fast: false
      matrix:
        run: [1]
      max-parallel: 3
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Test
        uses: ./.github/actions/terratest
        with:
          args: -run TestGKE
    env:
      TF_VAR_gcloud_credentials_base64: ${{ secrets.GCloudCredentialsBase64 }}
      TF_VAR_cluster_name: test-${{ github.run_id }}-${{matrix.run}}
