name: 'Test'
on: [push]

jobs:
  civo:
    runs-on: ubuntu-latest
    name: Civo
    strategy:
      matrix:
        run: [1,2,3]
      max-parallel: 3
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Test
        uses: ./.github/actions/terratest
        with:
          args: -run TestCivo
    env:
      TF_VAR_civo_api_key: ${{ secrets.CivoApiKey }}
      TF_VAR_cluster_name: test-cluster-${{matrix.run}}
  do:
    runs-on: ubuntu-latest
    name: DigitalOcean
    continue-on-error: true
    strategy:
      matrix:
        run: [1,2,3]
      max-parallel: 3
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Test
        uses: ./.github/actions/terratest
        with:
          args: -run TestDigitalOcean
    env:
      RUN: ${{ matrix.run }}
      TF_VAR_digitalocean_token: ${{ secrets.DigitalOceanToken }}
      TF_VAR_cluster_name: test-cluster-${{matrix.run}}
  gke:
    runs-on: ubuntu-latest
    name: GKE
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Test
        uses: ./.github/actions/terratest
        with:
          args: -run TestGKE
    env:
      TF_VAR_gcloud_credentials_base64: ${{ secrets.GCloudCredentialsBase64 }}
