name: 'Test'
on: [push]

jobs:
  civo:
    runs-on: ubuntu-latest
    name: Civo
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Test
        uses: ./.github/actions/terratest
        with:
          args: -run TestCivo
    env:
      TF_VAR_civo_api_key: ${{ secrets.CivoApiKey }}
  do:
    runs-on: ubuntu-latest
    name: DigitalOcean
    strategy:
      matrix:
        run: [1,2,3,4,5]
      max-parallel: 1
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: Test
        uses: ./.github/actions/terratest
        with:
          args: -run TestDigitalOcean
    env:
      RUN: ${{ matrix.run }}
      TF_VAR_digitalocean_token: ${{ secrets.DigitalOceanToken }}
